gText_HowMayIServeYou::
	.string "Welcome!\p"
	.string "How may I serve you?$"

gText_PleaseComeAgain::
	.string "Please come again!$"

gText_PlayerWhatCanIDoForYou::
	.string "{PLAYER}{STRING 5}, welcome!\p"
	.string "What can I do for you?$"

gText_FromundaSells::
	.string "I'm selling some rare items.\p"
	.string "You buyin' anything?$"

gText_FromundaByes::
	.string "I be smoking these rocks.$"

gText_FromundaSellsCandies::
	.string "Hey, kid…\p"
	.string "You want some candy?$"

gText_FromundaByesCandies::
	.string "Come back if you want another fix.$"
